version: "3.8" # Version de Compose
name: woodytoys # Nom du projet
services:
  internal_web: # Nom du conteneur
    build: ./internal_web
    volumes:
      - ./internal_web/nginx:/usr/share/nginx
    links: # Liaison avec d'autres conteneurs
      - db:db
    ports: # Port hôte -> Port conteneur
      - 80:80
      - 443:443
    networks: # Réseau associé
      secure_zone:
        ipv4_address: 192.168.0.3
  db:
    build: ./db
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      secure_zone:
        ipv4_address: 192.168.0.4
  dns:
    build: ./resolver
    ports:
      - 53:53/udp
      - 53:53
    volumes:
      - ./resolver/named.conf:/etc/bind/named.conf
      #- ./resolv.conf:/etc/resolv.conf
      - ./resolver/woodytoys.lab.named.conf:/etc/bind/woodytoys.lab.named.conf
      - ./resolver/woodytoys.lab:/etc/bind/woodytoys.lab
      - ./resolver/woodytoys.lab.rr.zone:/etc/bind/woodytoys.lab.rr.zone
    networks:
      secure_zone:
        ipv4_address: 192.168.0.2
        # 192.168.0.2 pour le SOA?
volumes: # Définition des volumes
  db-data:
networks:
  secure_zone:
    ipam:
      driver: default
      config: 
        - subnet: 192.168.0.0/16
          gateway: 192.168.0.1